name = "AdHydraulics"
uuid = "3359d19a-f7fc-4281-946f-263dff42c0a5"
authors = ["Xiaofeng Liu"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
